environment:
  global:
    VisualStudio: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
  #  freetype_version: "2-10-2"
  matrix:
  - library: static
  # library: shared
  
platform:
  - x86
  - amd64
  
configuration:
  - release
  - debug

init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Submodules
  - git submodule init
  - git submodule update
  # Get freetype2 source from GIT
  - ps: ./load-podofo.ps1 
  # Load libraries (zlib, libpng, freetype)
  - ps: ./EZTools/load-library.ps1 "ZLib"      $env:platform $env:configuration
  - ps: ./EZTools/load-library.ps1 "libpng"    $env:platform $env:configuration
  - ps: ./EZTools/load-library.ps1 "libjpeg"   $env:platform $env:configuration
  - ps: ./EZTools/load-library.ps1 "freetype"  $env:platform $env:configuration
  
build_script:
  - ps: ./build-podofo.ps1 $env:platform $env:configuration
  - ps: ./EZTools/install-pdb.ps1  ./d ./podofo/build podofo,podofo_static

after_build:
  - cd d
  - 7z a -tzip -r -y ..\podofo-%platform%-%configuration%.zip *.*
  
test: off

artifacts:
 - path: 'podofo-%platform%-%configuration%.zip'

deploy:
- provider: GitHub
# I am tagging through github
# Tag format is v<major version>.<minor version>, shall be consistent with major.monir of Appveyor build
# release: v$(appveyor_build_version)
  description: 'podofo appveyor build script [$(appveyor_build_version)] with binaries'
  auth_token:
    secure: 7fz/vsEpOOUyPYNmrykrY4lgqu3XQsag6g4x25nOwtd2dM2kc3X3GPoPzMCMDno/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
